version: '3.4'
cap_add:
  - SYS_PTRACE
services:
  netdata:
    image: titpetric/netdata
    container_name: netdata
    restart: always
    ports:
      - 19999:19999
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
